# Generated by Django 6.0.3 on 2026-03-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt khi nhận hàng'), ('card', 'Thẻ tín dụng / Ghi nợ'), ('transfer', 'Chuyển khoản Ngân hàng')], default='cash', max_length=20),
        ),
    ]
